# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pBdWc6Je_RkPvoYBmB7_OESDrqEDiqL
"""

import numpy as np
import pandas as pd

seq1=["com",'pew','ter','sci','ence']
seq2=['com','pew','ter','sci','unce']
seq3=['com','pew','tah','sci','unce']
seq4=['cam','pur','ter','sci','unce']
seq5=['com','pyo','ter','sanse']
seq6=['com','pi','oh','tah','sci','ens','ah']

ulang=8
for i in range(ulang):
    if ulang==2 or ulang==7:
        if len(seq6[ulang])!=len(seq1[ulang]):
            seq1.insert(i,"-")
        if len(seq6[ulang])!=len(seq2[ulang]):
            seq2.insert(i,"-")
        if len(seq6[ulang])!=len(seq3[ulang]):
            seq3.insert(ulang,"-")
        if len(seq6[ulang])!=len(seq4[ulang]):
            seq4.insert(ulang,"-")
        if len(seq6[ulang])!=len(seq5[ulang]):
            seq5.insert(ulang,"-")
    elif ulang==5:
        if len(seq5[ulang])!=len(seq1[ulang]): 
            seq5.insert(ulang,"-")
        else: continue

print(seq1)
print(seq2)
print(seq3)
print(seq4)
print(seq5)
print(seq6)

